import type { Metadata } from 'next'
import head from 'next/head'
import { Fragment } from 'react'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header_component/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Fragment>
      <head>
        <title>Jacob's Manual</title>
        <meta name="description"/>
        <link rel="icon" href="/images/icons/jacobIcon.png" />
      </head>
      <html lang="en">
        <body style={{margin: "0px", padding: "0px", overflow: "hidden"}} className={inter.className}>
        <Header/>
          {children}
        </body>
      </html>
    </Fragment>
  )
}
